on: 
  push:
    branches:
    - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Build Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'clique.zip'
          exclusions: '*.git*'

      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "clique.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: main
          tag: clique-wotlk-classic-${{ github.run_number }}